### ISSUE TITLE
Error using anaconda with python 3.6 

### ISSUE THREAD

**Issue by imihassan** [Bloodevil/sony_camera_api#68] opened 2021-03-16 11:41 UTC
I installed the module using pip install pysony.

To test I wrote code

`import pysony`
`api = pysony.SonyAPI()`
`api.getAvailableApiList()`

but it is giving this error ...

`SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[WORN] liveview is not a dict type")?`

**Comment by bjmc** [comment] 2021-03-16 12:01
This has already been fixed in #57.

I don't know how Anaconda decides what version to install, but if you get the latest version of this repo it should work with Python 3.

**Comment by bjmc** [comment] 2021-03-16 14:00
Duplicate of #61

**Comment by Bloodevil** [comment] 2022-03-23 21:25
close because there are duplicate issue.

**Closed as completed by Bloodevil** 2022-03-23 21:25 UTC
